version: '3.8'

services:
  db:
    image: postgres:15
    container_name: videos_db
    environment:
      - POSTGRES_DB=videos_db
      - POSTGRES_USER=videos_db_user_dev
      - POSTGRES_PASSWORD=123123123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/db/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
